default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v2.1.0
    hooks:
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: name-tests-test
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: flake8
        additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-deprecated',
        'flake8-meiqia',
        'flake8-mutable',
        'flake8-pep3101',
        'flake8-quotes',
        'flake8-string-format',
        'flake8-tidy-imports',
        ]
  - repo: https://github.com/pre-commit/pre-commit
    sha: v1.14.4
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/reorder_python_imports
    sha: v1.3.5
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/mirrors-autopep8
    sha: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/myint/docformatter
    rev: v1.1
    hooks:
      - id: docformatter
        args: ['--in-place', '--wrap-summaries=80', '--wrap-descriptions=80', '--pre-summary-newline']
